const OPEN_AUTHORISATION_MODAL = 'OPEN_MODAL';
const CLOSE_AUTHORISATION_MODAL = 'CLOSE_MODAL';

const OPEN_REGISTRATION_MODAL = 'OPEN_MODAL';
const CLOSE_REGISTRATION_MODAL = 'CLOSE_MODAL';

export {OPEN_AUTHORISATION_MODAL, CLOSE_AUTHORISATION_MODAL, OPEN_REGISTRATION_MODAL, CLOSE_REGISTRATION_MODAL}